### ISSUE TITLE
Update ncSOS mappings to match conventions/templates wherever possible

### ISSUE THREAD

**Issue by kknee** [asascience-open/ncSOS#175]
Based on: https://docs.google.com/spreadsheets/d/1vEw8kYDFmapibQsxDcN7hO4XSjX64zHrThVrMs6VZIg/edit?ts=564a6b4b#gid=1867084334

**Comment by abirger** [comment]
I have just noticed a pretty strange thing: although `station_id`, `profile_id`, and `trajectory_id` are claimed to be the only acceptable values of `cf_role` for Discrete Geometry CF data sets, the NCEI "timeSeries" and "timeSeriesProfile" templates somehow recommend to use `timeseries_id` value rather than seemingly correct `station_id` (see [here](https://docs.google.com/spreadsheets/d/1vEw8kYDFmapibQsxDcN7hO4XSjX64zHrThVrMs6VZIg/edit?ts=564a6b4b#gid=1306035718), [here](http://www.nodc.noaa.gov/data/formats/netcdf/v1.1/timeSeriesIncomplete.cdl), and [here](http://www.nodc.noaa.gov/data/formats/netcdf/v1.1/timeSeriesProfileIncomVIncomT.cdl)).

**Comment by abirger** [comment]
I have a concern about backward compatibility. The roadmap in the Wiki says that v1.3 "will be backwards compatible so that all of the datasets that currently work with ncSOS will continue to work with this version." How will that work if the mapping is changed, when ncSOS v1.3 and v1.1 would likely look for different netCDF attributes?

**Comment by lukecampbell** [comment]
timeseries_id is an acceptable value per CF 1.6

> The only acceptable values of `cf_role` for Discrete Geometry CF data sets are `timeseries_id` , `profile_id` , and `trajectory_id`.

**Comment by abirger** [comment]
@lukecampbell , Oops, you are right, it is the other way around - `timeseries_id` is acceptable while `station_id` is not. It means that the NCEI templates are correct but their description is faulty. Nothing can be trusted nowadays...

**Comment by cheryldmorse** [comment]
Updated to agree with the SOS / NetCDF mapping document. Commits f140141f26a8b0c5781489b522b7cabeaa33496f, 82fec8e58ab477989c55d719d103980d840b5cdc, d05b9457908b4e1941cfa1ccc6a7fda771805e77, ef9b18a7b251edf2f11899125da3312111274d02
